### ISSUE TITLE
website?

### ISSUE THREAD

**Issue by 0u44** [SirCryptic/cwv-scanner#1]
You had a website on this repository "(Demo)Website" just wondering, did you get rid of it?

**Comment by SirCryptic** [comment]
@CPScript 
> You had a website on this repository "(Demo)Website" just wondering, did you get rid of it?

no you can still find it in my basic website portfolio [here](https://sircryptic.github.io/Basic-Websites-Portfolio/) although it does output different results using bash compared to php html / js

**Comment by 0u44** [comment]
ok thx
